<a href="https://colab.research.google.com/github/Zohadeve/Zohadeve/blob/main/TITANIC_SURVIVAL_PREDICTION.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **TITANIC SURVIVAL PREDICTION**

In [ ]:
import pandas as pd

# Load the Titanic dataset
file_path = '/content/archive (6).zip'  # Adjust the path if necessary
titanic_data = pd.read_csv(file_path)

# Display the columns of the dataset
print(titanic_data.columns)

Index(['iso_code', 'continent', 'location', 'date', 'total_cases', 'new_cases',
       'new_cases_smoothed', 'total_deaths', 'new_deaths',
       'new_deaths_smoothed', 'total_cases_per_million',
       'new_cases_per_million', 'new_cases_smoothed_per_million',
       'total_deaths_per_million', 'new_deaths_per_million',
       'new_deaths_smoothed_per_million', 'reproduction_rate', 'icu_patients',
       'icu_patients_per_million', 'hosp_patients',
       'hosp_patients_per_million', 'weekly_icu_admissions',
       'weekly_icu_admissions_per_million', 'weekly_hosp_admissions',
       'weekly_hosp_admissions_per_million', 'total_tests', 'new_tests',
       'total_tests_per_thousand', 'new_tests_per_thousand',
       'new_tests_smoothed', 'new_tests_smoothed_per_thousand',
       'positive_rate', 'tests_per_case', 'tests_units', 'total_vaccinations',
       'people_vaccinated', 'people_fully_vaccinated', 'total_boosters',
       'new_vaccinations', 'new_vaccinations_smoothed',
       'total_vaccinations_per_hundred', 'people_vaccinated_per_hundred',
       'people_fully_vaccinated_per_hundred', 'total_boosters_per_hundred',
       'new_vaccinations_smoothed_per_million',
       'new_people_vaccinated_smoothed',
       'new_people_vaccinated_smoothed_per_hundred', 'stringency_index',
       'population', 'population_density', 'median_age', 'aged_65_older',
       'aged_70_older', 'gdp_per_capita', 'extreme_poverty',
       'cardiovasc_death_rate', 'diabetes_prevalence', 'female_smokers',
       'male_smokers', 'handwashing_facilities', 'hospital_beds_per_thousand',
       'life_expectancy', 'human_development_index',
       'excess_mortality_cumulative_absolute', 'excess_mortality_cumulative',
       'excess_mortality', 'excess_mortality_cumulative_per_million'],
      dtype='object')

In [ ]:
# Display basic information about the dataset
titanic_data.info()

# Check for missing values
print(titanic_data.isnull().sum())

# Fill missing values in the 'Age' column if it exists
if 'Age' in titanic_data.columns:
    titanic_data['Age'].fillna(titanic_data['Age'].median(), inplace=True)

# Fill missing values in the 'Embarked' column if it exists
if 'Embarked' in titanic_data.columns:
    titanic_data['Embarked'].fillna(titanic_data['Embarked'].mode()[0], inplace=True)

# Drop the 'Cabin' column if it exists as it has many missing values
if 'Cabin' in titanic_data.columns:
    titanic_data.drop(columns=['Cabin'], inplace=True)

# Drop rows with missing values in the 'Fare' column if it exists
if 'Fare' in titanic_data.columns:
    titanic_data.dropna(subset=['Fare'], inplace=True)

# Display the cleaned dataset info
titanic_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 949 entries, 0 to 948
Data columns (total 67 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   iso_code                                    949 non-null    object
 1   continent                                   949 non-null    object
 2   location                                    949 non-null    object
 3   date                                        949 non-null    object
 4   total_cases                                 949 non-null    int64
 5   new_cases                                   949 non-null    int64
 6   new_cases_smoothed                          944 non-null    float64
 7   total_deaths                                927 non-null    float64
 8   new_deaths                                  927 non-null    float64
 9   new_deaths_smoothed                         922 non-null    float64
 10  total_cases_per_million                     949 non-null    float64
 11  new_cases_per_million                       949 non-null    float64
 12  new_cases_smoothed_per_million              944 non-null    float64
 13  total_deaths_per_million                    927 non-null    float64
 14  new_deaths_per_million                      927 non-null    float64
 15  new_deaths_smoothed_per_million             922 non-null    float64
 16  reproduction_rate                           927 non-null    float64
 17  icu_patients                                0 non-null      float64
 18  icu_patients_per_million                    0 non-null      float64
 19  hosp_patients                               0 non-null      float64
 20  hosp_patients_per_million                   0 non-null      float64
 21  weekly_icu_admissions                       0 non-null      float64
 22  weekly_icu_admissions_per_million           0 non-null      float64
 23  weekly_hosp_admissions                      0 non-null      float64
 24  weekly_hosp_admissions_per_million          0 non-null      float64
 25  total_tests                                 679 non-null    float64
 26  new_tests                                   603 non-null    float64
 27  total_tests_per_thousand                    679 non-null    float64
 28  new_tests_per_thousand                      603 non-null    float64
 29  new_tests_smoothed                          828 non-null    float64
 30  new_tests_smoothed_per_thousand             828 non-null    float64
 31  positive_rate                               828 non-null    float64
 32  tests_per_case                              820 non-null    float64
 33  tests_units                                 835 non-null    object
 34  total_vaccinations                          311 non-null    float64
 35  people_vaccinated                           302 non-null    float64
 36  people_fully_vaccinated                     270 non-null    float64
 37  total_boosters                              157 non-null    float64
 38  new_vaccinations                            203 non-null    float64
 39  new_vaccinations_smoothed                   604 non-null    float64
 40  total_vaccinations_per_hundred              311 non-null    float64
 41  people_vaccinated_per_hundred               302 non-null    float64
 42  people_fully_vaccinated_per_hundred         270 non-null    float64
 43  total_boosters_per_hundred                  157 non-null    float64
 44  new_vaccinations_smoothed_per_million       604 non-null    float64
 45  new_people_vaccinated_smoothed              604 non-null    float64
 46  new_people_vaccinated_smoothed_per_hundred  604 non-null    float64
 47  stringency_index                            938 non-null    float64
 48  population                                  949 non-null    int64
 49  population_density                          949 non-null    float64
 50  median_age                                  949 non-null    float64
 51  aged_65_older                               949 non-null    float64
 52  aged_70_older                               949 non-null    float64
 53  gdp_per_capita                              949 non-null    float64
 54  extreme_poverty                             949 non-null    int64
 55  cardiovasc_death_rate                       949 non-null    float64
 56  diabetes_prevalence                         949 non-null    float64
 57  female_smokers                              949 non-null    float64
 58  male_smokers                                949 non-null    float64
 59  handwashing_facilities                      949 non-null    float64
 60  hospital_beds_per_thousand                  949 non-null    float64
 61  life_expectancy                             949 non-null    float64
 62  human_development_index                     949 non-null    float64
 63  excess_mortality_cumulative_absolute        0 non-null      float64
 64  excess_mortality_cumulative                 0 non-null      float64
 65  excess_mortality                            0 non-null      float64
 66  excess_mortality_cumulative_per_million     0 non-null      float64
dtypes: float64(58), int64(4), object(5)
memory usage: 496.9+ KB
iso_code                                     0
continent                                    0
location                                     0
date                                         0
total_cases                                  0
                                          ...
human_development_index                      0
excess_mortality_cumulative_absolute       949
excess_mortality_cumulative                949
excess_mortality                           949
excess_mortality_cumulative_per_million    949
Length: 67, dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 949 entries, 0 to 948
Data columns (total 67 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   iso_code                                    949 non-null    object
 1   continent                                   949 non-null    object
 2   location                                    949 non-null    object
 3   date                                        949 non-null    object
 4   total_cases                                 949 non-null    int64
 5   new_cases                                   949 non-null    int64
 6   new_cases_smoothed                          944 non-null    float64
 7   total_deaths                                927 non-null    float64
 8   new_deaths                                  927 non-null    float64
 9   new_deaths_smoothed                         922 non-null    float64
 10  total_cases_per_million                     949 non-null    float64
 11  new_cases_per_million                       949 non-null    float64
 12  new_cases_smoothed_per_million              944 non-null    float64
 13  total_deaths_per_million                    927 non-null    float64
 14  new_deaths_per_million                      927 non-null    float64
 15  new_deaths_smoothed_per_million             922 non-null    float64
 16  reproduction_rate                           927 non-null    float64
 17  icu_patients                                0 non-null      float64
 18  icu_patients_per_million                    0 non-null      float64
 19  hosp_patients                               0 non-null      float64
 20  hosp_patients_per_million                   0 non-null      float64
 21  weekly_icu_admissions                       0 non-null      float64
 22  weekly_icu_admissions_per_million           0 non-null      float64
 23  weekly_hosp_admissions                      0 non-null      float64
 24  weekly_hosp_admissions_per_million          0 non-null      float64
 25  total_tests                                 679 non-null    float64
 26  new_tests                                   603 non-null    float64
 27  total_tests_per_thousand                    679 non-null    float64
 28  new_tests_per_thousand                      603 non-null    float64
 29  new_tests_smoothed                          828 non-null    float64
 30  new_tests_smoothed_per_thousand             828 non-null    float64
 31  positive_rate                               828 non-null    float64
 32  tests_per_case                              820 non-null    float64
 33  tests_units                                 835 non-null    object
 34  total_vaccinations                          311 non-null    float64
 35  people_vaccinated                           302 non-null    float64
 36  people_fully_vaccinated                     270 non-null    float64
 37  total_boosters                              157 non-null    float64
 38  new_vaccinations                            203 non-null    float64
 39  new_vaccinations_smoothed                   604 non-null    float64
 40  total_vaccinations_per_hundred              311 non-null    float64
 41  people_vaccinated_per_hundred               302 non-null    float64
 42  people_fully_vaccinated_per_hundred         270 non-null    float64
 43  total_boosters_per_hundred                  157 non-null    float64
 44  new_vaccinations_smoothed_per_million       604 non-null    float64
 45  new_people_vaccinated_smoothed              604 non-null    float64
 46  new_people_vaccinated_smoothed_per_hundred  604 non-null    float64
 47  stringency_index                            938 non-null    float64
 48  population                                  949 non-null    int64
 49  population_density                          949 non-null    float64
 50  median_age                                  949 non-null    float64
 51  aged_65_older                               949 non-null    float64
 52  aged_70_older                               949 non-null    float64
 53  gdp_per_capita                              949 non-null    float64
 54  extreme_poverty                             949 non-null    int64
 55  cardiovasc_death_rate                       949 non-null    float64
 56  diabetes_prevalence                         949 non-null    float64
 57  female_smokers                              949 non-null    float64
 58  male_smokers                                949 non-null    float64
 59  handwashing_facilities                      949 non-null    float64
 60  hospital_beds_per_thousand                  949 non-null    float64
 61  life_expectancy                             949 non-null    float64
 62  human_development_index                     949 non-null    float64
 63  excess_mortality_cumulative_absolute        0 non-null      float64
 64  excess_mortality_cumulative                 0 non-null      float64
 65  excess_mortality                            0 non-null      float64
 66  excess_mortality_cumulative_per_million     0 non-null      float64
dtypes: float64(58), int64(4), object(5)
memory usage: 496.9+ KB

In [ ]:
# Display basic information about the dataset
titanic_data.info()

# Check for missing values
print(titanic_data.isnull().sum())

# Fill missing values in the 'Age' column if it exists
if 'Age' in titanic_data.columns:
    titanic_data['Age'].fillna(titanic_data['Age'].median(), inplace=True)

# Fill missing values in the 'Embarked' column if it exists
if 'Embarked' in titanic_data.columns:
    titanic_data['Embarked'].fillna(titanic_data['Embarked'].mode()[0], inplace=True)

# Drop the 'Cabin' column if it exists as it has many missing values
if 'Cabin' in titanic_data.columns:
    titanic_data.drop(columns=['Cabin'], inplace=True)

# Drop rows with missing values in the 'Fare' column if it exists
if 'Fare' in titanic_data.columns:
    titanic_data.dropna(subset=['Fare'], inplace=True)

# Display the cleaned dataset info
titanic_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 949 entries, 0 to 948
Data columns (total 67 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   iso_code                                    949 non-null    object
 1   continent                                   949 non-null    object
 2   location                                    949 non-null    object
 3   date                                        949 non-null    object
 4   total_cases                                 949 non-null    int64
 5   new_cases                                   949 non-null    int64
 6   new_cases_smoothed                          944 non-null    float64
 7   total_deaths                                927 non-null    float64
 8   new_deaths                                  927 non-null    float64
 9   new_deaths_smoothed                         922 non-null    float64
 10  total_cases_per_million                     949 non-null    float64
 11  new_cases_per_million                       949 non-null    float64
 12  new_cases_smoothed_per_million              944 non-null    float64
 13  total_deaths_per_million                    927 non-null    float64
 14  new_deaths_per_million                      927 non-null    float64
 15  new_deaths_smoothed_per_million             922 non-null    float64
 16  reproduction_rate                           927 non-null    float64
 17  icu_patients                                0 non-null      float64
 18  icu_patients_per_million                    0 non-null      float64
 19  hosp_patients                               0 non-null      float64
 20  hosp_patients_per_million                   0 non-null      float64
 21  weekly_icu_admissions                       0 non-null      float64
 22  weekly_icu_admissions_per_million           0 non-null      float64
 23  weekly_hosp_admissions                      0 non-null      float64
 24  weekly_hosp_admissions_per_million          0 non-null      float64
 25  total_tests                                 679 non-null    float64
 26  new_tests                                   603 non-null    float64
 27  total_tests_per_thousand                    679 non-null    float64
 28  new_tests_per_thousand                      603 non-null    float64
 29  new_tests_smoothed                          828 non-null    float64
 30  new_tests_smoothed_per_thousand             828 non-null    float64
 31  positive_rate                               828 non-null    float64
 32  tests_per_case                              820 non-null    float64
 33  tests_units                                 835 non-null    object
 34  total_vaccinations                          311 non-null    float64
 35  people_vaccinated                           302 non-null    float64
 36  people_fully_vaccinated                     270 non-null    float64
 37  total_boosters                              157 non-null    float64
 38  new_vaccinations                            203 non-null    float64
 39  new_vaccinations_smoothed                   604 non-null    float64
 40  total_vaccinations_per_hundred              311 non-null    float64
 41  people_vaccinated_per_hundred               302 non-null    float64
 42  people_fully_vaccinated_per_hundred         270 non-null    float64
 43  total_boosters_per_hundred                  157 non-null    float64
 44  new_vaccinations_smoothed_per_million       604 non-null    float64
 45  new_people_vaccinated_smoothed              604 non-null    float64
 46  new_people_vaccinated_smoothed_per_hundred  604 non-null    float64
 47  stringency_index                            938 non-null    float64
 48  population                                  949 non-null    int64
 49  population_density                          949 non-null    float64
 50  median_age                                  949 non-null    float64
 51  aged_65_older                               949 non-null    float64
 52  aged_70_older                               949 non-null    float64
 53  gdp_per_capita                              949 non-null    float64
 54  extreme_poverty                             949 non-null    int64
 55  cardiovasc_death_rate                       949 non-null    float64
 56  diabetes_prevalence                         949 non-null    float64
 57  female_smokers                              949 non-null    float64
 58  male_smokers                                949 non-null    float64
 59  handwashing_facilities                      949 non-null    float64
 60  hospital_beds_per_thousand                  949 non-null    float64
 61  life_expectancy                             949 non-null    float64
 62  human_development_index                     949 non-null    float64
 63  excess_mortality_cumulative_absolute        0 non-null      float64
 64  excess_mortality_cumulative                 0 non-null      float64
 65  excess_mortality                            0 non-null      float64
 66  excess_mortality_cumulative_per_million     0 non-null      float64
dtypes: float64(58), int64(4), object(5)
memory usage: 496.9+ KB
iso_code                                     0
continent                                    0
location                                     0
date                                         0
total_cases                                  0
                                          ...
human_development_index                      0
excess_mortality_cumulative_absolute       949
excess_mortality_cumulative                949
excess_mortality                           949
excess_mortality_cumulative_per_million    949
Length: 67, dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 949 entries, 0 to 948
Data columns (total 67 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   iso_code                                    949 non-null    object
 1   continent                                   949 non-null    object
 2   location                                    949 non-null    object
 3   date                                        949 non-null    object
 4   total_cases                                 949 non-null    int64
 5   new_cases                                   949 non-null    int64
 6   new_cases_smoothed                          944 non-null    float64
 7   total_deaths                                927 non-null    float64
 8   new_deaths                                  927 non-null    float64
 9   new_deaths_smoothed                         922 non-null    float64
 10  total_cases_per_million                     949 non-null    float64
 11  new_cases_per_million                       949 non-null    float64
 12  new_cases_smoothed_per_million              944 non-null    float64
 13  total_deaths_per_million                    927 non-null    float64
 14  new_deaths_per_million                      927 non-null    float64
 15  new_deaths_smoothed_per_million             922 non-null    float64
 16  reproduction_rate                           927 non-null    float64
 17  icu_patients                                0 non-null      float64
 18  icu_patients_per_million                    0 non-null      float64
 19  hosp_patients                               0 non-null      float64
 20  hosp_patients_per_million                   0 non-null      float64
 21  weekly_icu_admissions                       0 non-null      float64
 22  weekly_icu_admissions_per_million           0 non-null      float64
 23  weekly_hosp_admissions                      0 non-null      float64
 24  weekly_hosp_admissions_per_million          0 non-null      float64
 25  total_tests                                 679 non-null    float64
 26  new_tests                                   603 non-null    float64
 27  total_tests_per_thousand                    679 non-null    float64
 28  new_tests_per_thousand                      603 non-null    float64
 29  new_tests_smoothed                          828 non-null    float64
 30  new_tests_smoothed_per_thousand             828 non-null    float64
 31  positive_rate                               828 non-null    float64
 32  tests_per_case                              820 non-null    float64
 33  tests_units                                 835 non-null    object
 34  total_vaccinations                          311 non-null    float64
 35  people_vaccinated                           302 non-null    float64
 36  people_fully_vaccinated                     270 non-null    float64
 37  total_boosters                              157 non-null    float64
 38  new_vaccinations                            203 non-null    float64
 39  new_vaccinations_smoothed                   604 non-null    float64
 40  total_vaccinations_per_hundred              311 non-null    float64
 41  people_vaccinated_per_hundred               302 non-null    float64
 42  people_fully_vaccinated_per_hundred         270 non-null    float64
 43  total_boosters_per_hundred                  157 non-null    float64
 44  new_vaccinations_smoothed_per_million       604 non-null    float64
 45  new_people_vaccinated_smoothed              604 non-null    float64
 46  new_people_vaccinated_smoothed_per_hundred  604 non-null    float64
 47  stringency_index                            938 non-null    float64
 48  population                                  949 non-null    int64
 49  population_density                          949 non-null    float64
 50  median_age                                  949 non-null    float64
 51  aged_65_older                               949 non-null    float64
 52  aged_70_older                               949 non-null    float64
 53  gdp_per_capita                              949 non-null    float64
 54  extreme_poverty                             949 non-null    int64
 55  cardiovasc_death_rate                       949 non-null    float64
 56  diabetes_prevalence                         949 non-null    float64
 57  female_smokers                              949 non-null    float64
 58  male_smokers                                949 non-null    float64
 59  handwashing_facilities                      949 non-null    float64
 60  hospital_beds_per_thousand                  949 non-null    float64
 61  life_expectancy                             949 non-null    float64
 62  human_development_index                     949 non-null    float64
 63  excess_mortality_cumulative_absolute        0 non-null      float64
 64  excess_mortality_cumulative                 0 non-null      float64
 65  excess_mortality                            0 non-null      float64
 66  excess_mortality_cumulative_per_million     0 non-null      float64
dtypes: float64(58), int64(4), object(5)
memory usage: 496.9+ KB

In [ ]:
# Display basic information about the dataset
titanic_data.info()

# Check for missing values
print(titanic_data.isnull().sum())

# Fill missing values in the 'Age' column if it exists
if 'Age' in titanic_data.columns:
    titanic_data['Age'].fillna(titanic_data['Age'].median(), inplace=True)

# Fill missing values in the 'Embarked' column if it exists
if 'Embarked' in titanic_data.columns:
    titanic_data['Embarked'].fillna(titanic_data['Embarked'].mode()[0], inplace=True)

# Drop the 'Cabin' column if it exists as it has many missing values
if 'Cabin' in titanic_data.columns:
    titanic_data.drop(columns=['Cabin'], inplace=True)

# Drop rows with missing values in the 'Fare' column if it exists
if 'Fare' in titanic_data.columns:
    titanic_data.dropna(subset=['Fare'], inplace=True)

# Display the cleaned dataset info
titanic_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 949 entries, 0 to 948
Data columns (total 67 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   iso_code                                    949 non-null    object
 1   continent                                   949 non-null    object
 2   location                                    949 non-null    object
 3   date                                        949 non-null    object
 4   total_cases                                 949 non-null    int64
 5   new_cases                                   949 non-null    int64
 6   new_cases_smoothed                          944 non-null    float64
 7   total_deaths                                927 non-null    float64
 8   new_deaths                                  927 non-null    float64
 9   new_deaths_smoothed                         922 non-null    float64
 10  total_cases_per_million                     949 non-null    float64
 11  new_cases_per_million                       949 non-null    float64
 12  new_cases_smoothed_per_million              944 non-null    float64
 13  total_deaths_per_million                    927 non-null    float64
 14  new_deaths_per_million                      927 non-null    float64
 15  new_deaths_smoothed_per_million             922 non-null    float64
 16  reproduction_rate                           927 non-null    float64
 17  icu_patients                                0 non-null      float64
 18  icu_patients_per_million                    0 non-null      float64
 19  hosp_patients                               0 non-null      float64
 20  hosp_patients_per_million                   0 non-null      float64
 21  weekly_icu_admissions                       0 non-null      float64
 22  weekly_icu_admissions_per_million           0 non-null      float64
 23  weekly_hosp_admissions                      0 non-null      float64
 24  weekly_hosp_admissions_per_million          0 non-null      float64
 25  total_tests                                 679 non-null    float64
 26  new_tests                                   603 non-null    float64
 27  total_tests_per_thousand                    679 non-null    float64
 28  new_tests_per_thousand                      603 non-null    float64
 29  new_tests_smoothed                          828 non-null    float64
 30  new_tests_smoothed_per_thousand             828 non-null    float64
 31  positive_rate                               828 non-null    float64
 32  tests_per_case                              820 non-null    float64
 33  tests_units                                 835 non-null    object
 34  total_vaccinations                          311 non-null    float64
 35  people_vaccinated                           302 non-null    float64
 36  people_fully_vaccinated                     270 non-null    float64
 37  total_boosters                              157 non-null    float64
 38  new_vaccinations                            203 non-null    float64
 39  new_vaccinations_smoothed                   604 non-null    float64
 40  total_vaccinations_per_hundred              311 non-null    float64
 41  people_vaccinated_per_hundred               302 non-null    float64
 42  people_fully_vaccinated_per_hundred         270 non-null    float64
 43  total_boosters_per_hundred                  157 non-null    float64
 44  new_vaccinations_smoothed_per_million       604 non-null    float64
 45  new_people_vaccinated_smoothed              604 non-null    float64
 46  new_people_vaccinated_smoothed_per_hundred  604 non-null    float64
 47  stringency_index                            938 non-null    float64
 48  population                                  949 non-null    int64
 49  population_density                          949 non-null    float64
 50  median_age                                  949 non-null    float64
 51  aged_65_older                               949 non-null    float64
 52  aged_70_older                               949 non-null    float64
 53  gdp_per_capita                              949 non-null    float64
 54  extreme_poverty                             949 non-null    int64
 55  cardiovasc_death_rate                       949 non-null    float64
 56  diabetes_prevalence                         949 non-null    float64
 57  female_smokers                              949 non-null    float64
 58  male_smokers                                949 non-null    float64
 59  handwashing_facilities                      949 non-null    float64
 60  hospital_beds_per_thousand                  949 non-null    float64
 61  life_expectancy                             949 non-null    float64
 62  human_development_index                     949 non-null    float64
 63  excess_mortality_cumulative_absolute        0 non-null      float64
 64  excess_mortality_cumulative                 0 non-null      float64
 65  excess_mortality                            0 non-null      float64
 66  excess_mortality_cumulative_per_million     0 non-null      float64
dtypes: float64(58), int64(4), object(5)
memory usage: 496.9+ KB
iso_code                                     0
continent                                    0
location                                     0
date                                         0
total_cases                                  0
                                          ...
human_development_index                      0
excess_mortality_cumulative_absolute       949
excess_mortality_cumulative                949
excess_mortality                           949
excess_mortality_cumulative_per_million    949
Length: 67, dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 949 entries, 0 to 948
Data columns (total 67 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   iso_code                                    949 non-null    object
 1   continent                                   949 non-null    object
 2   location                                    949 non-null    object
 3   date                                        949 non-null    object
 4   total_cases                                 949 non-null    int64
 5   new_cases                                   949 non-null    int64
 6   new_cases_smoothed                          944 non-null    float64
 7   total_deaths                                927 non-null    float64
 8   new_deaths                                  927 non-null    float64
 9   new_deaths_smoothed                         922 non-null    float64
 10  total_cases_per_million                     949 non-null    float64
 11  new_cases_per_million                       949 non-null    float64
 12  new_cases_smoothed_per_million              944 non-null    float64
 13  total_deaths_per_million                    927 non-null    float64
 14  new_deaths_per_million                      927 non-null    float64
 15  new_deaths_smoothed_per_million             922 non-null    float64
 16  reproduction_rate                           927 non-null    float64
 17  icu_patients                                0 non-null      float64
 18  icu_patients_per_million                    0 non-null      float64
 19  hosp_patients                               0 non-null      float64
 20  hosp_patients_per_million                   0 non-null      float64
 21  weekly_icu_admissions                       0 non-null      float64
 22  weekly_icu_admissions_per_million           0 non-null      float64
 23  weekly_hosp_admissions                      0 non-null      float64
 24  weekly_hosp_admissions_per_million          0 non-null      float64
 25  total_tests                                 679 non-null    float64
 26  new_tests                                   603 non-null    float64
 27  total_tests_per_thousand                    679 non-null    float64
 28  new_tests_per_thousand                      603 non-null    float64
 29  new_tests_smoothed                          828 non-null    float64
 30  new_tests_smoothed_per_thousand             828 non-null    float64
 31  positive_rate                               828 non-null    float64
 32  tests_per_case                              820 non-null    float64
 33  tests_units                                 835 non-null    object
 34  total_vaccinations                          311 non-null    float64
 35  people_vaccinated                           302 non-null    float64
 36  people_fully_vaccinated                     270 non-null    float64
 37  total_boosters                              157 non-null    float64
 38  new_vaccinations                            203 non-null    float64
 39  new_vaccinations_smoothed                   604 non-null    float64
 40  total_vaccinations_per_hundred              311 non-null    float64
 41  people_vaccinated_per_hundred               302 non-null    float64
 42  people_fully_vaccinated_per_hundred         270 non-null    float64
 43  total_boosters_per_hundred                  157 non-null    float64
 44  new_vaccinations_smoothed_per_million       604 non-null    float64
 45  new_people_vaccinated_smoothed              604 non-null    float64
 46  new_people_vaccinated_smoothed_per_hundred  604 non-null    float64
 47  stringency_index                            938 non-null    float64
 48  population                                  949 non-null    int64
 49  population_density                          949 non-null    float64
 50  median_age                                  949 non-null    float64
 51  aged_65_older                               949 non-null    float64
 52  aged_70_older                               949 non-null    float64
 53  gdp_per_capita                              949 non-null    float64
 54  extreme_poverty                             949 non-null    int64
 55  cardiovasc_death_rate                       949 non-null    float64
 56  diabetes_prevalence                         949 non-null    float64
 57  female_smokers                              949 non-null    float64
 58  male_smokers                                949 non-null    float64
 59  handwashing_facilities                      949 non-null    float64
 60  hospital_beds_per_thousand                  949 non-null    float64
 61  life_expectancy                             949 non-null    float64
 62  human_development_index                     949 non-null    float64
 63  excess_mortality_cumulative_absolute        0 non-null      float64
 64  excess_mortality_cumulative                 0 non-null      float64
 65  excess_mortality                            0 non-null      float64
 66  excess_mortality_cumulative_per_million     0 non-null      float64
dtypes: float64(58), int64(4), object(5)
memory usage: 496.9+ KB

In [ ]:
# Display basic information about the dataset
titanic_data.info()

# Check for missing values
print(titanic_data.isnull().sum())

# Fill missing values in the 'Age' column if it exists
if 'Age' in titanic_data.columns:
    titanic_data['Age'].fillna(titanic_data['Age'].median(), inplace=True)

# Fill missing values in the 'Embarked' column if it exists
if 'Embarked' in titanic_data.columns:
    titanic_data['Embarked'].fillna(titanic_data['Embarked'].mode()[0], inplace=True)

# Drop the 'Cabin' column if it exists as it has many missing values
if 'Cabin' in titanic_data.columns:
    titanic_data.drop(columns=['Cabin'], inplace=True)

# Drop rows with missing values in the 'Fare' column if it exists
if 'Fare' in titanic_data.columns:
    titanic_data.dropna(subset=['Fare'], inplace=True)

# Display the cleaned dataset info
titanic_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 949 entries, 0 to 948
Data columns (total 67 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   iso_code                                    949 non-null    object
 1   continent                                   949 non-null    object
 2   location                                    949 non-null    object
 3   date                                        949 non-null    object
 4   total_cases                                 949 non-null    int64
 5   new_cases                                   949 non-null    int64
 6   new_cases_smoothed                          944 non-null    float64
 7   total_deaths                                927 non-null    float64
 8   new_deaths                                  927 non-null    float64
 9   new_deaths_smoothed                         922 non-null    float64
 10  total_cases_per_million                     949 non-null    float64
 11  new_cases_per_million                       949 non-null    float64
 12  new_cases_smoothed_per_million              944 non-null    float64
 13  total_deaths_per_million                    927 non-null    float64
 14  new_deaths_per_million                      927 non-null    float64
 15  new_deaths_smoothed_per_million             922 non-null    float64
 16  reproduction_rate                           927 non-null    float64
 17  icu_patients                                0 non-null      float64
 18  icu_patients_per_million                    0 non-null      float64
 19  hosp_patients                               0 non-null      float64
 20  hosp_patients_per_million                   0 non-null      float64
 21  weekly_icu_admissions                       0 non-null      float64
 22  weekly_icu_admissions_per_million           0 non-null      float64
 23  weekly_hosp_admissions                      0 non-null      float64
 24  weekly_hosp_admissions_per_million          0 non-null      float64
 25  total_tests                                 679 non-null    float64
 26  new_tests                                   603 non-null    float64
 27  total_tests_per_thousand                    679 non-null    float64
 28  new_tests_per_thousand                      603 non-null    float64
 29  new_tests_smoothed                          828 non-null    float64
 30  new_tests_smoothed_per_thousand             828 non-null    float64
 31  positive_rate                               828 non-null    float64
 32  tests_per_case                              820 non-null    float64
 33  tests_units                                 835 non-null    object
 34  total_vaccinations                          311 non-null    float64
 35  people_vaccinated                           302 non-null    float64
 36  people_fully_vaccinated                     270 non-null    float64
 37  total_boosters                              157 non-null    float64
 38  new_vaccinations                            203 non-null    float64
 39  new_vaccinations_smoothed                   604 non-null    float64
 40  total_vaccinations_per_hundred              311 non-null    float64
 41  people_vaccinated_per_hundred               302 non-null    float64
 42  people_fully_vaccinated_per_hundred         270 non-null    float64
 43  total_boosters_per_hundred                  157 non-null    float64
 44  new_vaccinations_smoothed_per_million       604 non-null    float64
 45  new_people_vaccinated_smoothed              604 non-null    float64
 46  new_people_vaccinated_smoothed_per_hundred  604 non-null    float64
 47  stringency_index                            938 non-null    float64
 48  population                                  949 non-null    int64
 49  population_density                          949 non-null    float64
 50  median_age                                  949 non-null    float64
 51  aged_65_older                               949 non-null    float64
 52  aged_70_older                               949 non-null    float64
 53  gdp_per_capita                              949 non-null    float64
 54  extreme_poverty                             949 non-null    int64
 55  cardiovasc_death_rate                       949 non-null    float64
 56  diabetes_prevalence                         949 non-null    float64
 57  female_smokers                              949 non-null    float64
 58  male_smokers                                949 non-null    float64
 59  handwashing_facilities                      949 non-null    float64
 60  hospital_beds_per_thousand                  949 non-null    float64
 61  life_expectancy                             949 non-null    float64
 62  human_development_index                     949 non-null    float64
 63  excess_mortality_cumulative_absolute        0 non-null      float64
 64  excess_mortality_cumulative                 0 non-null      float64
 65  excess_mortality                            0 non-null      float64
 66  excess_mortality_cumulative_per_million     0 non-null      float64
dtypes: float64(58), int64(4), object(5)
memory usage: 496.9+ KB
iso_code                                     0
continent                                    0
location                                     0
date                                         0
total_cases                                  0
                                          ...
human_development_index                      0
excess_mortality_cumulative_absolute       949
excess_mortality_cumulative                949
excess_mortality                           949
excess_mortality_cumulative_per_million    949
Length: 67, dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 949 entries, 0 to 948
Data columns (total 67 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   iso_code                                    949 non-null    object
 1   continent                                   949 non-null    object
 2   location                                    949 non-null    object
 3   date                                        949 non-null    object
 4   total_cases                                 949 non-null    int64
 5   new_cases                                   949 non-null    int64
 6   new_cases_smoothed                          944 non-null    float64
 7   total_deaths                                927 non-null    float64
 8   new_deaths                                  927 non-null    float64
 9   new_deaths_smoothed                         922 non-null    float64
 10  total_cases_per_million                     949 non-null    float64
 11  new_cases_per_million                       949 non-null    float64
 12  new_cases_smoothed_per_million              944 non-null    float64
 13  total_deaths_per_million                    927 non-null    float64
 14  new_deaths_per_million                      927 non-null    float64
 15  new_deaths_smoothed_per_million             922 non-null    float64
 16  reproduction_rate                           927 non-null    float64
 17  icu_patients                                0 non-null      float64
 18  icu_patients_per_million                    0 non-null      float64
 19  hosp_patients                               0 non-null      float64
 20  hosp_patients_per_million                   0 non-null      float64
 21  weekly_icu_admissions                       0 non-null      float64
 22  weekly_icu_admissions_per_million           0 non-null      float64
 23  weekly_hosp_admissions                      0 non-null      float64
 24  weekly_hosp_admissions_per_million          0 non-null      float64
 25  total_tests                                 679 non-null    float64
 26  new_tests                                   603 non-null    float64
 27  total_tests_per_thousand                    679 non-null    float64
 28  new_tests_per_thousand                      603 non-null    float64
 29  new_tests_smoothed                          828 non-null    float64
 30  new_tests_smoothed_per_thousand             828 non-null    float64
 31  positive_rate                               828 non-null    float64
 32  tests_per_case                              820 non-null    float64
 33  tests_units                                 835 non-null    object
 34  total_vaccinations                          311 non-null    float64
 35  people_vaccinated                           302 non-null    float64
 36  people_fully_vaccinated                     270 non-null    float64
 37  total_boosters                              157 non-null    float64
 38  new_vaccinations                            203 non-null    float64
 39  new_vaccinations_smoothed                   604 non-null    float64
 40  total_vaccinations_per_hundred              311 non-null    float64
 41  people_vaccinated_per_hundred               302 non-null    float64
 42  people_fully_vaccinated_per_hundred         270 non-null    float64
 43  total_boosters_per_hundred                  157 non-null    float64
 44  new_vaccinations_smoothed_per_million       604 non-null    float64
 45  new_people_vaccinated_smoothed              604 non-null    float64
 46  new_people_vaccinated_smoothed_per_hundred  604 non-null    float64
 47  stringency_index                            938 non-null    float64
 48  population                                  949 non-null    int64
 49  population_density                          949 non-null    float64
 50  median_age                                  949 non-null    float64
 51  aged_65_older                               949 non-null    float64
 52  aged_70_older                               949 non-null    float64
 53  gdp_per_capita                              949 non-null    float64
 54  extreme_poverty                             949 non-null    int64
 55  cardiovasc_death_rate                       949 non-null    float64
 56  diabetes_prevalence                         949 non-null    float64
 57  female_smokers                              949 non-null    float64
 58  male_smokers                                949 non-null    float64
 59  handwashing_facilities                      949 non-null    float64
 60  hospital_beds_per_thousand                  949 non-null    float64
 61  life_expectancy                             949 non-null    float64
 62  human_development_index                     949 non-null    float64
 63  excess_mortality_cumulative_absolute        0 non-null      float64
 64  excess_mortality_cumulative                 0 non-null      float64
 65  excess_mortality                            0 non-null      float64
 66  excess_mortality_cumulative_per_million     0 non-null      float64
dtypes: float64(58), int64(4), object(5)
memory usage: 496.9+ KB

In [ ]:
# Convert 'Sex' column to numerical values if it exists
if 'Sex' in titanic_data.columns:
    titanic_data['Sex'] = titanic_data['Sex'].map({'male': 0, 'female': 1})

# Convert 'Embarked' column to numerical values if it exists
if 'Embarked' in titanic_data.columns:
    titanic_data = pd.get_dummies(titanic_data, columns=['Embarked'], drop_first=True)

# Create a new feature 'FamilySize' if 'SibSp' and 'Parch' exist
if 'SibSp' in titanic_data.columns and 'Parch' in titanic_data.columns:
    titanic_data['FamilySize'] = titanic_data['SibSp'] + titanic_data['Parch']

# Drop unnecessary columns if they exist
columns_to_drop = ['Name', 'Ticket', 'SibSp', 'Parch']
columns_to_drop = [col for col in columns_to_drop if col in titanic_data.columns]
titanic_data.drop(columns=columns_to_drop, inplace=True)

# Display the first few rows of the modified dataset
print(titanic_data.head())

  iso_code continent  location       date  total_cases  new_cases  \
0      PAK      Asia  Pakistan  2/25/2020            2          2
1      PAK      Asia  Pakistan  2/26/2020            2          0
2      PAK      Asia  Pakistan  2/27/2020            2          0
3      PAK      Asia  Pakistan  2/28/2020            4          2
4      PAK      Asia  Pakistan  2/29/2020            4          0

   new_cases_smoothed  total_deaths  new_deaths  new_deaths_smoothed  ...  \
0                 NaN           NaN         NaN                  NaN  ...
1                 NaN           NaN         NaN                  NaN  ...
2                 NaN           NaN         NaN                  NaN  ...
3                 NaN           NaN         NaN                  NaN  ...
4                 NaN           NaN         NaN                  NaN  ...

   female_smokers  male_smokers  handwashing_facilities  \
0             2.8          36.7                  59.607
1             2.8          36.7                  59.607
2             2.8          36.7                  59.607
3             2.8          36.7                  59.607
4             2.8          36.7                  59.607

   hospital_beds_per_thousand  life_expectancy  human_development_index  \
0                         0.6            67.27                    0.557
1                         0.6            67.27                    0.557
2                         0.6            67.27                    0.557
3                         0.6            67.27                    0.557
4                         0.6            67.27                    0.557

   excess_mortality_cumulative_absolute  excess_mortality_cumulative  \
0                                   NaN                          NaN
1                                   NaN                          NaN
2                                   NaN                          NaN
3                                   NaN                          NaN
4                                   NaN                          NaN

   excess_mortality  excess_mortality_cumulative_per_million
0               NaN                                      NaN
1               NaN                                      NaN
2               NaN                                      NaN
3               NaN                                      NaN
4               NaN                                      NaN

[5 rows x 67 columns]

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Ensure 'Survived' column exists
if 'Survived' in titanic_data.columns:
    # Define the features and target variable
    X = titanic_data.drop(columns=['Survived'])
    y = titanic_data['Survived']

    # Split the data into training and testing sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # Initialize and train the Random Forest classifier
    model = RandomForestClassifier(n_estimators=100, random_state=42)
    model.fit(X_train, y_train)

    # Make predictions on the test set
    y_pred = model.predict(X_test)

    # Evaluate the model
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)

    print(f"Accuracy: {accuracy:.2f}")
    print(f"Precision: {precision:.2f}")
    print(f"Recall: {recall:.2f}")
    print(f"F1 Score: {f1:.2f}")
else:
    print("The 'Survived' column is missing from the dataset.")

The 'Survived' column is missing from the dataset.

# MOVIE RATING PREDICTION

In [ ]:
# Load the IMDb India Movies dataset with specified encoding
file_path = '/content/IMDb Movies India.csv'  # Adjust the path if necessary
movies_data = pd.read_csv(file_path, encoding='ISO-8859-1')

# Display the first few rows of the dataset
print(movies_data.head())

                                 Name    Year Duration            Genre  \
0                                         NaN      NaN            Drama
1  #Gadhvi (He thought he was Gandhi)  (2019)  109 min            Drama
2                         #Homecoming  (2021)   90 min   Drama, Musical
3                             #Yaaram  (2019)  110 min  Comedy, Romance
4                   ...And Once Again  (2010)  105 min            Drama

   Rating Votes            Director       Actor 1             Actor 2  \
0     NaN   NaN       J.S. Randhawa      Manmauji              Birbal
1     7.0     8       Gaurav Bakshi  Rasika Dugal      Vivek Ghamande
2     NaN   NaN  Soumyajit Majumdar  Sayani Gupta   Plabita Borthakur
3     4.4    35          Ovais Khan       Prateik          Ishita Raj
4     NaN   NaN        Amol Palekar  Rajat Kapoor  Rituparna Sengupta

           Actor 3
0  Rajendra Bhatia
1    Arvind Jangid
2       Roy Angana
3  Siddhant Kapoor
4      Antara Mali

In [ ]:
# Check the column names in movies_data
print(movies_data.columns)

# Ensure the columns exist before attempting to drop them
if all(col in movies_data.columns for col in ['genre', 'director', 'actors', 'avg_vote']):
    # Handle missing values and drop unnecessary columns
    movies_data.dropna(subset=['genre', 'director', 'actors', 'avg_vote'], inplace=True)
    movies_data.drop(columns=['title', 'year', 'date_published', 'duration', 'description', 'reviews_from_users', 'reviews_from_critics'], inplace=True)
else:
    print("One or more required columns are missing.")

Index(['Name', 'Year', 'Duration', 'Genre', 'Rating', 'Votes', 'Director',
       'Actor 1', 'Actor 2', 'Actor 3'],
      dtype='object')
One or more required columns are missing.

In [ ]:
import pandas as pd

# Load the dataset with the correct encoding specified
movies_data = pd.read_csv('/content/IMDb Movies India.csv', encoding='ISO-8859-1')

# Display basic information about the dataset
print(movies_data.head())
print(movies_data.info())

                                 Name    Year Duration            Genre  \
0                                         NaN      NaN            Drama
1  #Gadhvi (He thought he was Gandhi)  (2019)  109 min            Drama
2                         #Homecoming  (2021)   90 min   Drama, Musical
3                             #Yaaram  (2019)  110 min  Comedy, Romance
4                   ...And Once Again  (2010)  105 min            Drama

   Rating Votes            Director       Actor 1             Actor 2  \
0     NaN   NaN       J.S. Randhawa      Manmauji              Birbal
1     7.0     8       Gaurav Bakshi  Rasika Dugal      Vivek Ghamande
2     NaN   NaN  Soumyajit Majumdar  Sayani Gupta   Plabita Borthakur
3     4.4    35          Ovais Khan       Prateik          Ishita Raj
4     NaN   NaN        Amol Palekar  Rajat Kapoor  Rituparna Sengupta

           Actor 3
0  Rajendra Bhatia
1    Arvind Jangid
2       Roy Angana
3  Siddhant Kapoor
4      Antara Mali
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15509 entries, 0 to 15508
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      15509 non-null  object
 1   Year      14981 non-null  object
 2   Duration  7240 non-null   object
 3   Genre     13632 non-null  object
 4   Rating    7919 non-null   float64
 5   Votes     7920 non-null   object
 6   Director  14984 non-null  object
 7   Actor 1   13892 non-null  object
 8   Actor 2   13125 non-null  object
 9   Actor 3   12365 non-null  object
dtypes: float64(1), object(9)
memory usage: 1.2+ MB
None

In [ ]:
# Example assuming different column names
movies_data.dropna(subset=['Genre', 'Director'], inplace=True)
selected_columns = ['Genre', 'Director']
movies_data = movies_data[selected_columns]
print(movies_data.head())

             Genre            Director
0            Drama       J.S. Randhawa
1            Drama       Gaurav Bakshi
2   Drama, Musical  Soumyajit Majumdar
3  Comedy, Romance          Ovais Khan
4            Drama        Amol Palekar

<ipython-input-37-38024c730ffc>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_data.dropna(subset=['Genre', 'Director'], inplace=True)

In [ ]:
# Example of handling missing values and preparing for modeling
movies_data.dropna(subset=['Genre', 'Director'], inplace=True)
selected_columns = ['Genre', 'Director']
movies_data = movies_data[selected_columns]

# Additional preprocessing steps (e.g., feature engineering, encoding categorical variables) can follow here

In [ ]:
# Example assuming different column names or structure
# Check for the correct column names and structure in your actual DataFrame
movies_data.dropna(subset=['Genre', 'Director'], inplace=True)
selected_columns = ['Genre', 'Director']
movies_data = movies_data[selected_columns]

In [ ]:
import pandas as pd

# Load the dataset with the correct encoding specified
movies_data = pd.read_csv('/content/IMDb Movies India.csv', encoding='ISO-8859-1')

In [ ]:
print(movies_data.head())
print(movies_data.columns)

                                 Name    Year Duration            Genre  \
0                                         NaN      NaN            Drama
1  #Gadhvi (He thought he was Gandhi)  (2019)  109 min            Drama
2                         #Homecoming  (2021)   90 min   Drama, Musical
3                             #Yaaram  (2019)  110 min  Comedy, Romance
4                   ...And Once Again  (2010)  105 min            Drama

   Rating Votes            Director       Actor 1             Actor 2  \
0     NaN   NaN       J.S. Randhawa      Manmauji              Birbal
1     7.0     8       Gaurav Bakshi  Rasika Dugal      Vivek Ghamande
2     NaN   NaN  Soumyajit Majumdar  Sayani Gupta   Plabita Borthakur
3     4.4    35          Ovais Khan       Prateik          Ishita Raj
4     NaN   NaN        Amol Palekar  Rajat Kapoor  Rituparna Sengupta

           Actor 3
0  Rajendra Bhatia
1    Arvind Jangid
2       Roy Angana
3  Siddhant Kapoor
4      Antara Mali
Index(['Name', 'Year', 'Duration', 'Genre', 'Rating', 'Votes', 'Director',
       'Actor 1', 'Actor 2', 'Actor 3'],
      dtype='object')

In [ ]:
import pandas as pd

# Load the dataset
movies_data = pd.read_csv('/content/IMDb Movies India.csv', encoding='ISO-8859-1')

# Display basic information about the dataset
print(movies_data.head())
print(movies_data.columns)

                                 Name    Year Duration            Genre  \
0                                         NaN      NaN            Drama
1  #Gadhvi (He thought he was Gandhi)  (2019)  109 min            Drama
2                         #Homecoming  (2021)   90 min   Drama, Musical
3                             #Yaaram  (2019)  110 min  Comedy, Romance
4                   ...And Once Again  (2010)  105 min            Drama

   Rating Votes            Director       Actor 1             Actor 2  \
0     NaN   NaN       J.S. Randhawa      Manmauji              Birbal
1     7.0     8       Gaurav Bakshi  Rasika Dugal      Vivek Ghamande
2     NaN   NaN  Soumyajit Majumdar  Sayani Gupta   Plabita Borthakur
3     4.4    35          Ovais Khan       Prateik          Ishita Raj
4     NaN   NaN        Amol Palekar  Rajat Kapoor  Rituparna Sengupta

           Actor 3
0  Rajendra Bhatia
1    Arvind Jangid
2       Roy Angana
3  Siddhant Kapoor
4      Antara Mali
Index(['Name', 'Year', 'Duration', 'Genre', 'Rating', 'Votes', 'Director',
       'Actor 1', 'Actor 2', 'Actor 3'],
      dtype='object')

In [ ]:
import pandas as pd

# Load the dataset
movies_data = pd.read_csv('/content/IMDb Movies India.csv', encoding='ISO-8859-1')

# Print columns to verify correctness
print(movies_data.columns)

# Ensure column names match expected names
expected_columns = ['Genre', 'Director', 'Actor 1', 'Rating']
if not all(col in movies_data.columns for col in expected_columns):
    raise ValueError("Columns do not match expected names.")

# Drop rows with missing values in important columns
movies_data.dropna(subset=expected_columns, inplace=True)

# Select relevant columns for modeling
selected_columns = ['Genre', 'Director', 'Actor 1', 'Rating']
movies_data = movies_data[selected_columns]

# Continue with feature engineering, modeling, and evaluation steps...

Index(['Name', 'Year', 'Duration', 'Genre', 'Rating', 'Votes', 'Director',
       'Actor 1', 'Actor 2', 'Actor 3'],
      dtype='object')

In [ ]:
# Step 1: Load the Iris dataset
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import StandardScaler

# Load the Iris dataset
iris = load_iris()
X = iris.data  # Features (sepal length, sepal width, petal length, petal width)
y = iris.target  # Target (species)

# Step 2: Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 3: Preprocess the data (scaling)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Step 4: Choose a model (Support Vector Machine classifier)
model = SVC(kernel='rbf', random_state=42)

# Step 5: Train the model
model.fit(X_train_scaled, y_train)

# Step 6: Evaluate the model
y_pred = model.predict(X_test_scaled)

# Accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

# Classification report
print("Classification Report:")
print(classification_report(y_test, y_pred, target_names=iris.target_names))

# Confusion matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy: 1.00
Classification Report:
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

In [ ]:
# Import necessary libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

# Step 1: Load the dataset (hypothetical example)
# Replace with your actual dataset
data = {
    'Advertising_Expenditure': [100, 200, 300, 400, 500],
    'Target_Audience_Segmentation': ['Segment1', 'Segment2', 'Segment1', 'Segment3', 'Segment2'],
    'Advertising_Platform': ['Platform1', 'Platform2', 'Platform3', 'Platform1', 'Platform2'],
    'Sales': [1000, 2200, 3000, 3800, 4200]
}
df = pd.DataFrame(data)

# Step 2: Preprocess the data (encoding categorical variables, splitting data)
# Example encoding categorical variables
df_encoded = pd.get_dummies(df, columns=['Target_Audience_Segmentation', 'Advertising_Platform'])

X = df_encoded.drop('Sales', axis=1)
y = df_encoded['Sales']

# Step 3: Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 4: Choose a model and train it (using Linear Regression as an example)
model = LinearRegression()
model.fit(X_train, y_train)

# Step 5: Evaluate the model
y_pred = model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error: {mse}")

# Step 6: Make predictions (hypothetical example)
new_data = {
    'Advertising_Expenditure': [600],
    'Target_Audience_Segmentation_Segment1': [1],
    'Target_Audience_Segmentation_Segment2': [0],
    'Target_Audience_Segmentation_Segment3': [0],
    'Advertising_Platform_Platform1': [1],
    'Advertising_Platform_Platform2': [0],
    'Advertising_Platform_Platform3': [0]
}
df_new = pd.DataFrame(new_data)
predicted_sales = model.predict(df_new)
print(f"Predicted Sales: {predicted_sales[0]}")

Mean Squared Error: 534356.3418399198
Predicted Sales: 5551.661356395086

In [ ]:
# Import necessary libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import RandomUnderSampler
from imblearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

# Step 1: Load the dataset
df = pd.read_csv('/content/creditcard.csv')

# Step 2: Data Preprocessing
# Normalize numerical features (assuming 'amount' and 'balance' are numerical)
scaler = StandardScaler()
df[['amount', 'balance']] = scaler.fit_transform(df[['amount', 'balance']])

# Encode categorical features if any
# Example: df = pd.get_dummies(df, columns=['category'])

# Split data into features (X) and target (y)
X = df.drop('fraudulent', axis=1)
y = df['fraudulent']

# Step 3: Handle Class Imbalance using SMOTE (oversampling) or RandomUnderSampler (undersampling)
# Example with SMOTE
# oversampler = SMOTE(random_state=0)
# X_resampled, y_resampled = oversampler.fit_resample(X, y)

# Example with RandomUnderSampler
undersampler = RandomUnderSampler(random_state=0)
X_resampled, y_resampled = undersampler.fit_resample(X, y)

# Step 4: Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.2, random_state=42)

# Step 5: Model Selection and Training
# Example with Logistic Regression
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

# Example with Random Forest
# model = RandomForestClassifier(n_estimators=100, random_state=42)
# model.fit(X_train, y_train)

# Step 6: Model Evaluation
y_pred = model.predict(X_test)
print("Classification Report:")
print(classification_report(y_test, y_pred))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

KeyError: "None of [Index(['amount', 'balance'], dtype='object')] are in the [columns]"

In [ ]:
# Import necessary libraries
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

# Step 1: Load the dataset
df = pd.read_csv('/content/creditcard.csv')

# Step 2: Data Exploration (Optional)
# Check the columns in the dataset
print(df.columns)

# Step 3: Data Preprocessing
# Ensure column names match what's in your dataset
if 'amount' in df.columns and 'balance' in df.columns:
    # Normalize numerical features (assuming 'amount' and 'balance' are numerical)
    scaler = StandardScaler()
    df[['amount', 'balance']] = scaler.fit_transform(df[['amount', 'balance']])
else:
    raise KeyError("Columns 'amount' and/or 'balance' not found in the dataset.")

# Step 4: Split data into features (X) and target (y)
X = df.drop('fraudulent', axis=1)  # Adjust this based on your actual target column name
y = df['fraudulent']

# Step 5: Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Proceed with further steps (handling class imbalance, model training, evaluation)

Index(['Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10',
       'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20',
       'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Amount',
       'Class'],
      dtype='object')

KeyError: "Columns 'amount' and/or 'balance' not found in the dataset."

In [ ]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

# Step 1: Load the dataset
df = pd.read_csv('/content/creditcard.csv')

# Step 2: Data Exploration (Optional)
# Check the columns in the dataset
print(df.columns)

# Step 3: Data Preprocessing
# Check if 'amount' and 'balance' columns exist
if 'amount' in df.columns and 'balance' in df.columns:
    # Normalize numerical features (assuming 'amount' and 'balance' are numerical)
    scaler = StandardScaler()
    df[['amount', 'balance']] = scaler.fit_transform(df[['amount', 'balance']])
else:
    # Print columns if 'amount' and 'balance' are not found
    print("Columns 'amount' and/or 'balance' not found in the dataset.")

# Step 4: Split data into features (X) and target (y)
X = df.drop('fraudulent', axis=1)  # Adjust this based on your actual target column name
y = df['fraudulent']

# Step 5: Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Proceed with further steps (handling class imbalance, model training, evaluation)

Index(['Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10',
       'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20',
       'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Amount',
       'Class'],
      dtype='object')
Columns 'amount' and/or 'balance' not found in the dataset.

KeyError: "['fraudulent'] not found in axis"

In [ ]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

# Step 1: Load the dataset
df = pd.read_csv('/content/creditcard.csv')

# Step 2: Data Exploration (Optional)
# Check the columns in the dataset
print(df.columns)

# Step 3: Data Preprocessing
# Check if 'amount' and 'balance' columns exist
if 'amount' in df.columns and 'balance' in df.columns:
    # Normalize numerical features (assuming 'amount' and 'balance' are numerical)
    scaler = StandardScaler()
    df[['amount', 'balance']] = scaler.fit_transform(df[['amount', 'balance']])
else:
    # Print columns if 'amount' and 'balance' are not found
    print("Columns 'amount' and/or 'balance' not found in the dataset.")

# Step 4: Check if 'fraudulent' column exists
if 'fraudulent' in df.columns:
    # Split data into features (X) and target (y)
    X = df.drop('fraudulent', axis=1)  # Adjust this based on your actual target column name
    y = df['fraudulent']

    # Step 5: Split data into training and testing sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # Proceed with further steps (handling class imbalance, model training, evaluation)
else:
    print("Column 'fraudulent' not found in the dataset.")

Index(['Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10',
       'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20',
       'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Amount',
       'Class'],
      dtype='object')
Columns 'amount' and/or 'balance' not found in the dataset.
Column 'fraudulent' not found in the dataset.